import{_ as a}from"./plugin-vue_export-helper-DlAUqK2U.js";import{r as c,o as r,c as s,a as e,d as t,b as i,w as n}from"./app-CKRzqze-.js";const l={},p=e("p",null,"If you are sure that the verification data is correct, but you still keep getting this exception, please check the correctness of the token specified in the settings.",-1),h=e("h2",{id:"botexception",tabindex:"-1"},[e("a",{class:"header-anchor",href:"#botexception"},[e("span",null,"BotException")])],-1),d=e("h2",{id:"validationexception",tabindex:"-1"},[e("a",{class:"header-anchor",href:"#validationexception"},[e("span",null,"ValidationException")])],-1);function m(u,g){const o=c("RouteLink");return r(),s("div",null,[p,h,e("p",null,[t("The name of the bot you are trying to "),i(o,{to:"/en/docs/get-started/usage.html"},{default:n(()=>[t("apply")]),_:1}),t(" is incorrect, or the bot does not exist in the added list.")]),d,e("p",null,[t("Failed to validate the user with one of the "),i(o,{to:"/en/docs/validator/"},{default:n(()=>[t("available validators")]),_:1}),t(". It can potentially indicate a threat of hacking and/or bypassing the system.")])])}const y=a(l,[["render",m],["__file","exception.html.vue"]]),b=JSON.parse('{"path":"/en/docs/exception.html","title":"Exceptions","lang":"en-US","frontmatter":{"title":"Exceptions","icon":"bomb","order":4,"description":"If you are sure that the verification data is correct, but you still keep getting this exception, please check the correctness of the token specified in the settings. BotExcepti...","head":[["link",{"rel":"alternate","hreflang":"uk-ua","href":"https://tgwebvalid.com/docs/exception.html"}],["link",{"rel":"alternate","hreflang":"zh-cn","href":"https://tgwebvalid.com/zh/docs/exception.html"}],["meta",{"property":"og:url","content":"https://tgwebvalid.com/en/docs/exception.html"}],["meta",{"property":"og:site_name","content":"The PHP library for validate Telegram users"}],["meta",{"property":"og:title","content":"Exceptions"}],["meta",{"property":"og:description","content":"If you are sure that the verification data is correct, but you still keep getting this exception, please check the correctness of the token specified in the settings. BotExcepti..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"en-US"}],["meta",{"property":"og:locale:alternate","content":"uk-UA"}],["meta",{"property":"og:locale:alternate","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2024-03-21T16:00:03.000Z"}],["meta",{"property":"article:author","content":"Mr. Anonymous"}],["meta",{"property":"article:modified_time","content":"2024-03-21T16:00:03.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"Exceptions\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2024-03-21T16:00:03.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"Mr. Anonymous\\",\\"url\\":\\"https://github.com/CrazyTapok-bit\\"}]}"]]},"headers":[{"level":2,"title":"BotException","slug":"botexception","link":"#botexception","children":[]},{"level":2,"title":"ValidationException","slug":"validationexception","link":"#validationexception","children":[]}],"git":{"createdTime":1711036650000,"updatedTime":1711036803000,"contributors":[{"name":"Сергій","email":"61122611+CrazyTapok-bit@users.noreply.github.com","commits":2}]},"readingTime":{"minutes":0.28,"words":85},"filePathRelative":"en/docs/exception.md","localizedDate":"March 21, 2024","autoDesc":true}');export{y as comp,b as data};
